programs {
    $terminal = kitty
    $fileManager = dolphin
    $menu = wofi --show drun
    $menuAll = wofi --show run
}
$mainMod = SUPER

source = ~/.config/hypr/env.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/startup.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/style.conf
source = ~/.config/hypr/apps.conf
source = ~/.config/hypr/nav.conf

master {
    # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
    new_is_master = true
}

gestures {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    workspace_swipe = false
}

windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.
windowrule = immediate, class:^.*$


