[font]
size = 10.0

[colors.bright]
black = "#625e4c"
blue = "#9d65ff"
cyan = "#58d1eb"
green = "#98e024"
magenta = "#f4005f"
red = "#f4005f"
white = "#f6f6ef"
yellow = "#e0d561"

[colors.normal]
black = "#1a1a1a"
blue = "#9d65ff"
cyan = "#58d1eb"
green = "#98e024"
magenta = "#f4005f"
red = "#f4005f"
white = "#c4c5b5"
yellow = "#fa8419"

[colors.primary]
background = "#000000"
foreground = "#FFFFFF"

[font.bold]
family = "MesloLGS Nerd Font"
style = "Bold"

[font.italic]
family = "MesloLGS Nerd Font"
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Alt"
